site_name: ODE's Docs

theme:
  name: "material"

plugins:
  - mkdocstrings
  - search

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
  - mdx_math
  - pymdownx.arithmatex 

nav:
  - Inicio: index.md
  - Módulo ODE: reference.md


